name: Context Demo

on: 
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    Analysis:
        name: Erste Analyse
        runs-on: ubuntu-latest
        outputs:
          secret-message: ${{ steps.get_secret_message.outputs.message }}

        steps:
            - name: Commit Message lesen
              id: get_secret_message
              run: echo "message=Wuhuu!" >> "$GITHUB_OUTPUT"

            - name: Zeige GitHub Kontext
              run: echo '${{ toJson(github) }}'

            - name: Zeige Steps Kontext
              run: echo '${{ toJson(steps) }}'

            - name: Zeige Runner Kontext
              run: echo '${{ toJson(runner) }}'

    job2:
        name: Zeige Werte aus Job 1 (Analysis)
        runs-on: ubuntu-latest
        needs: Analysis
        
        steps:
          - name: Outputs anzeigen
            run: |
             echo "Geheime Message aus Job 1: ${{ needs.Analysis.outputs.secret-message }}"